set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TOOLCHAIN_PREFIX ${CMAKE_SYSTEM_PROCESSOR}-apple-darwin14)

set(CMAKE_C_COMPILER ${OSXCROSS_HOME}/bin/${TOOLCHAIN_PREFIX}-clang)
set(CMAKE_CXX_COMPILER ${OSXCROSS_HOME}/bin/${TOOLCHAIN_PREFIX}-clang++)

set(CMAKE_FIND_ROOT_PATH ${OSXCROSS_HOME}/SDK/MacOSX10.10.sdk)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_AR ${OSXCROSS_HOME}/bin/${TOOLCHAIN_PREFIX}-ar CACHE FILEPATH "ar")
set(CMAKE_RANLIB ${OSXCROSS_HOME}/bin/${TOOLCHAIN_PREFIX}-ranlib CACHE FILEPATH "ranlib")
set(CMAKE_INSTALL_NAME_TOOL ${OSXCROSS_HOME}/bin/${TOOLCHAIN_PREFIX}-install_name_tool CACHE FILEPATH "install_name_tool")
